# Generated by Django 3.0.8 on 2020-09-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
